import React, { PureComponent } from 'react';
import { PieChart, Pie, Sector, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import './SentimentAnalysis.scss';

//values to be presented on the charts generated by sentiment analysis
const chartStats = [
    { name: 'Positive', value: 400 },
    { name: 'Negative', value: 300 },
    { name: 'Neutral', value: 300 },
];

//colors used on the chart 
const COLORS = ['#41b8d5', '#31356e', '#6ce5e8'];


const RADIAN = Math.PI / 180;
const renderCustomizedLabel = ({ cx , cy, midAngle, innerRadius, outerRadius, percent, index }: 
    {
        cx: any, 
        cy:any, 
        midAngle: any,
        innerRadius:any, 
        outerRadius:any,
        percent:any,
        index:any
    } ) => {
    const radius = innerRadius + (outerRadius - innerRadius) * 0.5;
    const x = cx + radius * Math.cos(-midAngle * RADIAN);
    const y = cy + radius * Math.sin(-midAngle * RADIAN);

    return (
        <text x={x} y={y} fill="white" textAnchor={x > cx ? 'start' : 'end'} dominantBaseline="central">
            {`${(percent * 100).toFixed(0)}%`}
        </text>
  );
};

function SentimentAnalysis() {
    return (
        <div className='sentimentAnalysis'>
            <h1 className='title'>Sentiment Analysis</h1>
            {/* Graph */}
            <div className="graphSection">
                <div className="graph">
                    <ResponsiveContainer width="100%" height="100%">
                        <PieChart width={400} height={400}>
                            <Pie
                                data={chartStats}
                                cx="50%"
                                cy="50%"
                                labelLine={false}
                                // label={renderCustomizedLabel}
                                label
                                outerRadius={80}
                                fill="#8884d8"
                                dataKey="value"
                            >
                                {chartStats.map((entry, index) => (
                                <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                ))}
                            </Pie>
                            <Tooltip />
                        </PieChart>
                    </ResponsiveContainer>
                </div>
                <h3 className="teamName">Team name</h3>
                <p className="graphDescription">Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur</p>
            </div> 
        </div>
    );
}

export default SentimentAnalysis;